#!/bin/sh
#
# Start Dropbear SSH server
#

case "$1" in
  start)
    echo "Starting Dropbear SSH server..."
    /usr/sbin/dropbear -E -F &
    ;;
  stop)
    echo "Stopping Dropbear SSH server..."
    killall dropbear
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0